FROM ubuntu:22.04

WORKDIR /api-tests
RUN apt update
RUN apt install -y ruby-dev libffi-dev autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev libmysqlclient-dev
RUN gem install bundler
COPY Gemfile Gemfile
RUN bundle install

COPY --from=ghcr.io/ufoscout/docker-compose-wait:latest /wait /wait